"""Add profession to user

Revision ID: 0ca3ae8ca3d1
Revises: f24acde1e54f
Create Date: 2026-08-06 00:09:37.667586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca3ae8ca3d1'
down_revision: Union[str, None] = 'f24acde1e54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profession', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profession')
    # ### end Alembic commands ###
