"""add updated_at columns budget unique constraint and composite indexes

Revision ID: 3683139f3ae8
Revises: bd2a5b048c11
Create Date: 2026-08-14 16:19:45.560848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3683139f3ae8'
down_revision: Union[str, None] = 'bd2a5b048c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.create_index('ix_budgets_user_id_month_year', 'budgets', ['user_id', 'month', 'year'], unique=False)
    op.create_unique_constraint('uq_budgets_user_category_month_year', 'budgets', ['user_id', 'category_id', 'month', 'year'])
    op.drop_index(op.f('ix_insights_user_id'), table_name='insights')
    op.create_index('ix_insights_user_id_is_read', 'insights', ['user_id', 'is_read'], unique=False)
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.create_index('ix_transactions_user_id_transaction_date', 'transactions', ['user_id', 'transaction_date'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_index('ix_transactions_user_id_transaction_date', table_name='transactions')
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.drop_column('transactions', 'updated_at')
    op.drop_index('ix_insights_user_id_is_read', table_name='insights')
    op.create_index(op.f('ix_insights_user_id'), 'insights', ['user_id'], unique=False)
    op.drop_constraint('uq_budgets_user_category_month_year', 'budgets', type_='unique')
    op.drop_index('ix_budgets_user_id_month_year', table_name='budgets')
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.drop_column('budgets', 'updated_at')
    # ### end Alembic commands ###
